name: CI

on: [push, pull_request]

env:
  NEXT_PUBLIC_PRIMARY: #27509B
  NEXT_PUBLIC_BASE: https://www.amarjanica.com/projects/react-components

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 17.x ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Bootstrap
        run: npm i
      - name: Test and Build
        run: lerna run build --include-dependencies
      - name: Build Docs
        run: npm run docs:build
